### ISSUE TITLE
Example line numbers do not seem to match the source

### ISSUE THREAD

**Issue by kaukas** [icy-arctic-fox/spectator#18]
Having a spec file
```crystal
require "./spec_helper"

Spectator.describe Thing do
  it "works" do
    expect(false).to eq(true)
  end
end
```
`crystal spec` reports
```
     Failure: false does not equal true

         actual: false
       expected: true

     # spec/bisect_spec.cr:21
```
The example is defined at line 4 but (I suppose) after macro expansion it appears on line 21. This is a problem in case one uses tools like [vim-test](https://github.com/vim-test/vim-test#setup) which run the spec-under-cursor using the line number of `it`.

Can anything be done to make the line numbers match?

**Comment by kaukas** [comment]
Actually, I am not sure what's happening with the line numbers.
```crystal
require "./spec_helper"

Spectator.describe Bisect do
  it "fails on an empty array" do
    expect(false).to eq(true)
  end

  it "returns the only item" do
    expect(false).to eq(true)
  end

  it "calls the block and returns the item that the block is truthy for" do
    expect(false).to eq(true)
  end

  it "first verifies that all items are truthy" do
    expect(false).to eq(true)
  end
end
```
prints
```
Failed examples:

crystal spec spec/bisect_spec.cr:21 # Bisect fails on an empty array
crystal spec spec/bisect_spec.cr:7 # Bisect returns the only item
crystal spec spec/bisect_spec.cr:11 # Bisect calls the block and returns the item that the block is truthy for
crystal spec spec/bisect_spec.cr:15 # Bisect first verifies that all items are truthy
```
So the order is correct but the line numbers are somewhat random.

Also, the `spec` spec defined on lines 4-6
```crystal
  it "one" do
    false.should eq(true)
  end
```
can be invoked by calling any of
```
crystal spec spec/test_spec.cr:4
crystal spec spec/test_spec.cr:5
crystal spec spec/test_spec.cr:6
```
For spectator, only the exact line works.

**Comment by icy-arctic-fox** [comment]
There seems to be some issue with macro expansion and the original AST position information.

This should be fixed in the upcoming v0.10.0 code, I've verified the line numbers match up there. The fix can probably be back-ported to v0.9 of Spectator.

As for multi-line matching, that will likely need additional work to make possible.

**Comment by icy-arctic-fox** [comment]
This should be fixed in the latest release (0.9.31). Can you try it out and make sure it works on your end before we close this issue?

**Comment by kaukas** [comment]
I can confirm that running by line number picks the right `it`, thank you! That was very quick!

As you said, anywhere else in the spec still does not work.
