### ISSUE TITLE
`be_within` not respected during a `to have_received.with` check

### ISSUE THREAD

**Issue by anlek** [icy-arctic-fox/spectator#55]
I am not sure how to prove this is an issue, but given this test:

```cr
it "tracks the time it takes to run the block" do
  Timecop.freeze(Time.local) do
    expected_start_time = Time.local
    expected_end_time = expected_start_time + 10.seconds

    analytics.instrument(name: name, source: source) do
      Timecop.travel(expected_end_time)
    end

    expect(brain_talker).to have_received(:send).with(payload: {
      :group  => Analytics::Data::GROUP_NAME,
      :name   => name,
      :source => source,
      :start  => expected_start_time,
      :end    => be_within(1.second).of(expected_end_time),
    }, action: "analytics")
  end
end
```

I get this as a result:
```
Failure: brain_talker did not receive #send(payload: {:group => "CallCenter", :name => "Timetravel", :source => "my.time.travel.experiment", :start => 2024-01-26 17:26:57.022772000 -07:00 Local, :end => Spectator::Matchers::RangeMatcher(Range(Time, Time))(@expected=2024-01-26 17:27:07 -07:00 ± 1.second: 2024-01-26 17:27:06.022772000 -07:00 Local..2024-01-26 17:27:08.022772000 -07:00 Local)}, action: "analytics")

       expected: #send(payload: {:group => "CallCenter", :name => "Timetravel", :source => "my.time.travel.experiment", :start => 2024-01-26 17:26:57.022772000 -07:00 Local, :end => Spectator::Matchers::RangeMatcher(Range(Time, Time))(@expected=2024-01-26 17:27:07 -07:00 ± 1.second: 2024-01-26 17:27:06.022772000 -07:00 Local..2024-01-26 17:27:08.022772000 -07:00 Local)}, action: "analytics")
         actual: #tap(no args)
                 #send(payload: {:group => "CallCenter", :name => "Timetravel", :source => "my.time.travel.experiment", :start => 2024-01-26 17:26:57.022772000 -07:00 Local, :end => 2024-01-26 17:27:07.022773000 -07:00 Local}, action: "analytics")

     # spec/utils/analytics_spec.cr:135
```

Note that `end_time` is `2024-01-26 17:27:07.022773000 -07:00 Local` which is within `2024-01-26 17:27:06.022772000 -07:00 Local..2024-01-26 17:27:08.022772000 -07:00 Local`

I expected this test to pass. Am I missing something?

**Comment by icy-arctic-fox** [comment]
I suspect this is because matchers in spectator can't be [composed like they are in RSpec](https://rspec.info/features/3-12/rspec-expectations/composing-matchers/). It's literally comparing the time against a spectator object, which fails. This certainly should be a feature, but I'm unsure if implementing it would break anything else.

**Comment by icy-arctic-fox** [comment]
I've pushed a [branch](https://github.com/icy-arctic-fox/spectator/compare/master...composable-matchers) that hopefully resolves the issue. Can you try it and let me know if it works in your scenario?

Updating your shards.yml to:

```yml
development_dependencies:
  spectator:
    gitlab: arctic-fox/spectator
    branch: composable-matchers
```

and re-running `shards` should switch to the branch.

**Comment by anlek** [comment]
Wow, thank you! I'll give it a go shortly and get back to you.

**Comment by anlek** [comment]
Looks like it's still not working for me: My result looks like this:
```
Failures:

  1) Analytics#instrument when called with a block when not sending a start time tracks the time it takes to run the block
     Failure: brain_talker did not receive #send(payload: {:group => "CallCenter", :name => "Timetravel", :source => "my.time.travel.experiment", :start => 2024-01-29 15:48:07.280423000 -07:00 Local, :end => Spectator::Matchers::RangeMatcher(Range(Time, Time))(@expected=2024-01-29 15:48:17 -07:00 ± 1.second: 2024-01-29 15:48:16.280423000 -07:00 Local..2024-01-29 15:48:18.280423000 -07:00 Local)}, action: "analytics")

       expected: #send(payload: {:group => "CallCenter", :name => "Timetravel", :source => "my.time.travel.experiment", :start => 2024-01-29 15:48:07.280423000 -07:00 Local, :end => Spectator::Matchers::RangeMatcher(Range(Time, Time))(@expected=2024-01-29 15:48:17 -07:00 ± 1.second: 2024-01-29 15:48:16.280423000 -07:00 Local..2024-01-29 15:48:18.280423000 -07:00 Local)}, action: "analytics")
         actual: #tap(no args)
                 #send(payload: {:group => "CallCenter", :name => "Timetravel", :source => "my.time.travel.experiment", :start => 2024-01-29 15:48:07.280423000 -07:00 Local, :end => 2024-01-29 15:48:17.280424000 -07:00 Local}, action: "analytics")

     # spec/utils/analytics_spec.cr:138
```
Here is the list of installed shards.
<img width="296" alt="87661" src="https://github.com/icy-arctic-fox/spectator/assets/11052/c100e212-81cd-4904-8f89-0fba92c3a1da">

**Comment by anlek** [comment]
I just checked and the spectator hash `4a630b1` is the same hash on `main` as it is on the `composable-matchers` branch. Maybe I'm doing something incorrectly.  I can see there is code on that branch that's 6 commits ahead. I've even removed my lib directory and re-installed all the shards, it didn't help.

This is my dependencies:
![31911](https://github.com/icy-arctic-fox/spectator/assets/11052/afeca54c-1a6e-4fd7-834e-74b1e1b5c146)

**Comment by icy-arctic-fox** [comment]
Weird... that should have changed branches. Maybe try with `commit` as 9b1d400ee1f0edf0b979b0d113ea618b16e0deed instead of `branch`. If that doesn't work, then I guess we can try a tag or temporary version. I'm fairly certain I've done this before with other projects and it worked fine.

**Comment by anlek** [comment]
Happy to report that it worked (shard via commit) and all my tests are green! I even had to use a new one and that worked as expected:
![58070](https://github.com/icy-arctic-fox/spectator/assets/11052/796f3da1-577c-4f6a-ba62-e2ad014f5297)

I have 78 tests and they all seem to pass without an issue. Not sure how else I can test if your changes break other tests...

**Comment by anlek** [comment]
I now have 119 tests passing without an issue (using the composable-matchers 9b1d400 commit)

**Comment by icy-arctic-fox** [comment]
Glad to hear it works! :smile: 

I've pushed release v0.12.0, which contains the fix. The version bump should be manageable if anyone does see an issue with the changes.
